global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: monitoring

    static_configs:
      - targets: ['<public IP>:8080']

  - job_name: monitoring_manual

    static_configs:
      - targets: ['<public IP>:8500']
